# Generated by Django 4.2.6 on 2023-10-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roomFinder_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="title",
            field=models.CharField(default="blank", max_length=100),
            preserve_default=False,
        ),
    ]
