# Generated by Django 4.2.6 on 2023-11-01 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("roomFinder_app", "0002_reservation_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="approved",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="day",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="User",),
    ]
