# Generated by Django 4.2.4 on 2023-11-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roomFinder_app", "0003_reservation_approved_reservation_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="approved",
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
