# Generated by Django 4.2.6 on 2023-11-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roomFinder_app", "0005_rename_room_location_room_building_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="room_id",),
        migrations.AddField(
            model_name="room",
            name="room_name",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
    ]
