# Generated by Django 4.2.6 on 2023-11-07 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("roomFinder_app", "0006_remove_room_room_id_room_room_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="reservation", name="approved",),
        migrations.AddField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
