# Generated by Django 4.2.6 on 2023-11-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roomFinder_app", "0007_remove_reservation_approved_reservation_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="approved",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
