# Generated by Django 4.2.6 on 2023-11-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roomFinder_app", "0008_room_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
